name: terraform ci

on:
  workflow_dispatch:
    inputs:
      command:
        required: true
        description: terraform command
        default: plan

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pCYSl5EDgo/cat@master
        id: tf_version
        with:
          path: .terraform-version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.tf_version.outputs.text }}

      - name: Terraform Plan
        if: ${{ github.event.inputs.command == 'plan' }}
        working-directory: '.'
        run: |
          terraform init
          terraform validate
          terraform plan

      - name: Terraform Apply
        if: ${{ github.event.inputs.command == 'apply' }}
        working-directory: '.'
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.command == 'destroy' }}
        working-directory: '.'
        run: |
          terraform init
          terraform validate
          terraform destroy -auto-approve
